#Porta do Zuul Server 5555
server:
  port: ${PORT:5555}

#Configuracoes relacionadas ao registro no eureka
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
      healthcheck:
        enabled: true

#mapeamento do zuul
zuul:
  prefix:  /api/
  routes:
    bookws:  /bookws/**
    stockws: /stockws/**

# Ex: http://localhost:5555/api/bookws/v1/books

#Configuracoes relacionadas ao Actuator
info:
  app:
    name:@project.name@
    description:@project.description@
    version:@project.version@