#Porta do Zuul Server 5555
server:
  port: ${PORT:5555}

#Configuracoes relacionadas ao registro no eureka
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
      healthcheck:
        enabled: true

#Configuracoes relacionadas ao Actuator
info:
  app:
    name:@project.name@
    description:@project.description@
    version:@project.version@

#Habilitando URls Escondidas do Zuul    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        
#mapeamento do zuul
# Ex: http://localhost:5555/api/bookws/v1/books

zuul:
  routes:
    prefix:  /api/
    bookws:  /bookws/**
    stockws: /stockws/**
    authserver:      
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
  add-proxy-headers: true
 
security:
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://localhost:8769/auth/oauth/token
      userAuthorizationUri: /auth/oauth/authorize
      clientId: msc-clientapp
      clientSecret: msc123456
    resource:
      jwt:
        keyValue: "345345fsdfsf5345"
      id: openid
      serviceId: ${PREFIX:}resource

#Log Level
logging:
  level:
    org.springframework.security: DEBUG